### ISSUE TITLE
Unit Tests Call External Services

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/slp-sdk#5]
The scope of this issue is to refactor unit tests to mock any external service calls. The primary differences between unit and integration tests, is that unit tests do not call external services. External services need to be mocked for unit tests, and live for integration tests.

If unit tests make external calls, then any CI system relying on unit tests will fail when those services fail, and then bad things happen. The reliability of the CI system is thrown into question and the ability to push a fix fails if the CI can't pass tests and validate the PR.

I ran all tests on slp-sdk and they passed. But then I turned off my wifi and ran the tests again. The following tests failed:
```
561 passing (4s)
  5 failing

  1) #Utils
       #list
         should list all SLP tokens:
     Error: getaddrinfo ENOTFOUND rest.bitcoin.com rest.bitcoin.com:443
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)

  2) #Utils
       #list
         should list single SLP token by id: 4276533bb702e7f8c9afd8aa61ebf016e95011dc3d54e55faa847ac1dd461e84:
     Error: getaddrinfo ENOTFOUND rest.bitcoin.com rest.bitcoin.com:443
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)

  3) #Utils
       #balancesForAddress
         should fetch all balances for address: simpleledger:qr5agtachyxvrwxu76vzszan5pnvuzy8duhv4lxrsk:
     Error: getaddrinfo ENOTFOUND rest.bitcoin.com rest.bitcoin.com:443
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)

  4) #Utils
       #balance
         should fetch balance of single token for address: simpleledger:qr5agtachyxvrwxu76vzszan5pnvuzy8duhv4lxrsk:
     Error: getaddrinfo ENOTFOUND rest.bitcoin.com rest.bitcoin.com:443
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)

  5) #Utils
       #validateTxid
         should validate slp txid:
     Error: getaddrinfo ENOTFOUND rest.bitcoin.com rest.bitcoin.com:443
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)

```

For mocking external services, here is an example of how I mock Express:
https://github.com/Bitcoin-com/rest.bitcoin.com/blob/master/test/v2/mocks/express-mocks.js

And here is an example of a mocking library for BITBOX:
https://github.com/christroutner/bch-cli-wallet/blob/master/test/mocks/bitbox.js

**Comment by christroutner** [comment]
This Issue is resolved with PR #15 and npm version 1.1.12
